steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env']
    env:
      - 'NODE_ENV=${_NODE_ENV}'
      - 'PORT=${_PORT}'
      - 'MAILER_EMAIL=${_MAILER_EMAIL}'
      - 'SENDGRID_API_KEY=${_SENDGRID_API_KEY}'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tsavo-seed', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/tsavo-seed']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'tsavo-seed', '--image', 'gcr.io/$PROJECT_ID/tsavo-seed', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated', '--max-instances=5']
images:
  - 'gcr.io/$PROJECT_ID/tsavo-seed'